import { type PracticeProblem } from "../types/problem.js";

export const problemBank: PracticeProblem[] = [
  {
    platform: "leetcode",
    problemId: 1,
    title: "Two Sum",
    slug: "two-sum",
    difficulty: "easy",
    topics: ["arrays", "hash-map"],
    url: "https://leetcode.com/problems/two-sum/",
  },
  {
    platform: "leetcode",
    problemId: 121,
    title: "Best Time to Buy and Sell Stock",
    slug: "best-time-to-buy-and-sell-stock",
    difficulty: "easy",
    topics: ["arrays", "sliding-window"],
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    platform: "leetcode",
    problemId: 238,
    title: "Product of Array Except Self",
    slug: "product-of-array-except-self",
    difficulty: "medium",
    topics: ["arrays", "prefix-sum"],
    url: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    platform: "leetcode",
    problemId: 56,
    title: "Merge Intervals",
    slug: "merge-intervals",
    difficulty: "medium",
    topics: ["arrays", "sorting"],
    url: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    platform: "leetcode",
    problemId: 53,
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    difficulty: "medium",
    topics: ["arrays", "dp"],
    url: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    platform: "leetcode",
    problemId: 200,
    title: "Number of Islands",
    slug: "number-of-islands",
    difficulty: "medium",
    topics: ["graphs", "dfs", "bfs"],
    url: "https://leetcode.com/problems/number-of-islands/",
  },
  {
    platform: "leetcode",
    problemId: 207,
    title: "Course Schedule",
    slug: "course-schedule",
    difficulty: "medium",
    topics: ["graphs", "topological-sort"],
    url: "https://leetcode.com/problems/course-schedule/",
  },
  {
    platform: "leetcode",
    problemId: 300,
    title: "Longest Increasing Subsequence",
    slug: "longest-increasing-subsequence",
    difficulty: "medium",
    topics: ["dp", "binary-search"],
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
  },
  {
    platform: "leetcode",
    problemId: 322,
    title: "Coin Change",
    slug: "coin-change",
    difficulty: "medium",
    topics: ["dp"],
    url: "https://leetcode.com/problems/coin-change/",
  },
  {
    platform: "leetcode",
    problemId: 76,
    title: "Minimum Window Substring",
    slug: "minimum-window-substring",
    difficulty: "hard",
    topics: ["sliding-window", "hash-map"],
    url: "https://leetcode.com/problems/minimum-window-substring/",
  },
  {
    platform: "codeforces",
    problemId: "4A",
    title: "Watermelon",
    slug: "watermelon",
    difficulty: "easy",
    topics: ["math"],
    url: "https://codeforces.com/problemset/problem/4/A",
  },
  {
    platform: "codeforces",
    problemId: "71A",
    title: "Way Too Long Words",
    slug: "way-too-long-words",
    difficulty: "easy",
    topics: ["strings"],
    url: "https://codeforces.com/problemset/problem/71/A",
  },
  {
    platform: "codeforces",
    problemId: "158A",
    title: "Next Round",
    slug: "next-round",
    difficulty: "easy",
    topics: ["implementation"],
    url: "https://codeforces.com/problemset/problem/158/A",
  },
  {
    platform: "codechef",
    problemId: "FLOW001",
    title: "Add Two Numbers",
    slug: "add-two-numbers",
    difficulty: "easy",
    topics: ["implementation"],
    url: "https://www.codechef.com/problems/FLOW001",
  },
  {
    platform: "hackerrank",
    problemId: "arrays-ds",
    title: "Arrays DS",
    slug: "arrays-ds",
    difficulty: "easy",
    topics: ["arrays"],
    url: "https://www.hackerrank.com/challenges/arrays-ds/problem",
  },
  {
    platform: "hackerrank",
    problemId: "ctci-bfs-shortest-reach",
    title: "BFS Shortest Reach",
    slug: "bfs-shortest-reach",
    difficulty: "hard",
    topics: ["graphs", "bfs"],
    url: "https://www.hackerrank.com/challenges/ctci-bfs-shortest-reach/problem",
  },
];

